### ISSUE TITLE
auto.sh fails on Debian 10

### ISSUE THREAD

**Issue by macdroid53** [ceremcem/build-freecad-asm3#21]
Debian 10 system.
Attempted to run auto.sh 
Got the following error.

`

 lxc-create -n fc -t debian -- -r buster
./auto.sh: line 108: lxc-create: command not found
 set +x
./auto.sh: line 110: lxc-start: command not found

Couldn't start fc.
`

**Comment by ceremcem** [comment]
Please install LXC tools: 

```
sudo apt-get install lxc
```

**Comment by macdroid53** [comment]
Sure, this is obvious to me after goggling LXC and rereading the first paragraphs of your readme, it makes sense. But it is not explicitly called out out in your readme.

But...if I put on my naive "trying to use your tool" hat this makes the offering confusing.

I suppose it is ok to assume that if a user has found your github, they are some level and would see this as obvious.

But, I'd recommend adding a short note to the readme, just for completeness, maybe something that lists assumptions. Like: "it is assumed the following things: item, item, lxc,... are installed and are required before attempting to run auto.sh"

**Comment by ceremcem** [comment]
> But it is not explicitly called out out in your readme. 

Yes, I [added that](https://github.com/ceremcem/build-freecad-asm3#dependencies) after this issue. Thanks for reminding this one. 

Did this solve your issue or maybe you would need to `apt-get install lxc-templates`? Please let me know.

**Comment by macdroid53** [comment]
I added lxc and it has completed.

The resulting executable seems ok.

Did you see the differences I noted in the issue thread on the realthunder github?

Just curious...

**Comment by ceremcem** [comment]
> The resulting executable seems ok.

Okay, so can we close the issue? 

> Did you see the differences I noted in the issue thread on the realthunder github?

Yes. The packages are for additional workbenches, so the problem doesn't seem to be related with the dependencies. Realthunder pointed the Python issue, it's more likely some reason with your host environment. 

Note that the "container" approach is exactly for this kind of situations. As you can see, you now have a rock solid build environment with no runtime performance penalty. ;-)

**Comment by macdroid53** [comment]
Yes I believe this issue is closed.

I don't quite understand where the python lib difference came from...and it didn't result in a complete build.

But, of course, not related to here.

Thanks!

One, question though. This build doesn't seem to refer to the local .FreeCAD for the runtime config files. Where is looking?

**Comment by ceremcem** [comment]
> This build doesn't seem to refer to the local .FreeCAD for the runtime config files. Where is looking?

Since it completely runs within the container, everything is located inside the container. So you can either: 
* copy your local `~/.FreeCAD` directory to `/var/lib/lxc/fc/rootfs/home/aea/.FreeCAD` 
* or you can mount `~/.FreeCAD` directory to `/var/lib/lxc/fc/rootfs/home/aea/.FreeCAD` (see [Accessing your local files](https://github.com/ceremcem/build-freecad-asm3#accessing-your-local-files))

I wouldn't recommend mounting the `.FreeCAD` directory because by maintaining the `.FreeCAD` directory inside the container, you can take advantage of backing up the `.FreeCAD` directory when you backup `/var/lib/lxc/fc/rootfs`. 

Not related to this repository, but I would also recommend using BTRFS for containers, since backing up is a breeze.
